FROM node:18

WORKDIR /app

# copie o package.json do backend, NÃO o da raiz
COPY package.json ./
COPY package-lock.json ./

RUN npm install

# copie o restante dos arquivos do backend
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
